name: linting, testing, building

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.12.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install modules
        run: npm install

      - name: Build production project
        run: npm run build:prod
        if: always()

      #      - name: Linting for ts, js
      #        run: npm run lint:eslint
      #        if: always()

      - name: Linting for css, scss
        run: npm run lint:stylelint
        if: always()

      - name: Unit testing
        run: npm run test:unit
        if: always()

      - name: Screenshot testing
        run: npx chromatic --exit-zero-on-changes --project-token=$PROJECT_TOKEN -b storybook:build
        env:
          PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        if: always()
